# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sexo', models.CharField(max_length=1)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
